name       : mkchromecast
version    : 0.3.7.1
release    : 2
source     :
    - https://github.com/muammar/mkchromecast/archive/0.3.7.1.tar.gz : 99d162b030b2fbfaae7a9513bcb1250f84f5cc2ca9c596984d5261907d582257
license    : MIT
networking : yes
component  : multimedia.audio
summary    : Cast Linux Audio to your Google Cast Devices
description: |
    Cast Linux Audio to your Google Cast Devices
rundeps    :
    - ffmpeg
    - flask
    - libflac
    - libsoxr
    - mutagen
    - pulseaudio
    - pychromecast
    - python-itsdangerous
    - python-psutil
    - python-qt5
    - python-setuptools
    - youtube-dl
install    : |
    install -dm00644 $installdir/usr/share/mkchromecast/mkchromecast/getch
    install -dm00644 $installdir/usr/share/mkchromecast/images
    install -Dm00644 mkchromecast/*.py $installdir/usr/share/mkchromecast/mkchromecast/
    install -Dm00644 mkchromecast/getch/* $installdir/usr/share/mkchromecast/mkchromecast/getch/
    install -Dm00644 mkchromecast.py $installdir/usr/share/mkchromecast/
    install -Dm00644 images/* $installdir/usr/share/mkchromecast/images/
    install -Dm00755 $pkgfiles/mkchromecast.sh $installdir/usr/bin/mkchromecast
    install -Dm00644 $pkgfiles/mkchromecast.png $installdir/usr/share/pixmaps/mkchromecast.png
    install -Dm00644 $pkgfiles/mkchromecast.desktop $installdir/usr/share/applications/mkchromecast.desktop

